/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author admin
 */
public class MDIApplication extends javax.swing.JFrame {

    /**
     * Creates new form MDIApplication
     */
    
    private static MDIApplication instance;
    
    private MDIApplication() {
        setTitle("Gestion des Certifications Professionnelles");
        setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/image/professional-certification-icon-logo.png")).getImage());
        initComponents();
    }
    
    public static MDIApplication getInstance() {
        if (instance == null) {
            instance = new MDIApplication();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        certificationMenuItem = new javax.swing.JMenuItem();
        etudiantMenuItem = new javax.swing.JMenuItem();
        inscriptionMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        certificationParNomMenuItem = new javax.swing.JMenuItem();
        inscriptionParCertificationMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        certificationMenuItem.setMnemonic('o');
        certificationMenuItem.setText("Certification");
        certificationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificationMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(certificationMenuItem);

        etudiantMenuItem.setMnemonic('s');
        etudiantMenuItem.setText("Etudiant");
        etudiantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etudiantMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(etudiantMenuItem);

        inscriptionMenuItem.setMnemonic('a');
        inscriptionMenuItem.setText("Inscription");
        inscriptionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscriptionMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(inscriptionMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Statistiques");

        certificationParNomMenuItem.setMnemonic('t');
        certificationParNomMenuItem.setText("Rechercher un etudiant par certification ");
        certificationParNomMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificationParNomMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(certificationParNomMenuItem);

        inscriptionParCertificationMenuItem.setText("Filtrer les inscriptions par certification");
        inscriptionParCertificationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscriptionParCertificationMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(inscriptionParCertificationMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void etudiantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etudiantMenuItemActionPerformed
        closeAllInternalFrames();
        EtudiantForm ef = new EtudiantForm();
        desktopPane.add(ef);
        ef.setVisible(true);
        centerInternalFrame(ef);
    }//GEN-LAST:event_etudiantMenuItemActionPerformed

    private void certificationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificationMenuItemActionPerformed
        closeAllInternalFrames();
        CertificationForm cf = new CertificationForm();
        desktopPane.add(cf);
        cf.setVisible(true);
        centerInternalFrame(cf);
    }//GEN-LAST:event_certificationMenuItemActionPerformed

    private void inscriptionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscriptionMenuItemActionPerformed
        closeAllInternalFrames();
        InscriptionForm insf = new InscriptionForm();
        desktopPane.add(insf);
        insf.setVisible(true);
        centerInternalFrame(insf);
    }//GEN-LAST:event_inscriptionMenuItemActionPerformed

    private void closeAllInternalFrames() {
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            frame.dispose();
        }
    }

    private void centerInternalFrame(JInternalFrame internalFrame) {
        int x = (desktopPane.getWidth() - internalFrame.getWidth()) / 2;
        int y = (desktopPane.getHeight() - internalFrame.getHeight()) / 2;
        internalFrame.setLocation(x, y);
    }
    
    private void certificationParNomMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificationParNomMenuItemActionPerformed
        closeAllInternalFrames();
        EtudiantParCertification cpnf = new EtudiantParCertification();
        desktopPane.add(cpnf);
        cpnf.setVisible(true);
        centerInternalFrame(cpnf);
    }//GEN-LAST:event_certificationParNomMenuItemActionPerformed

    private void inscriptionParCertificationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscriptionParCertificationMenuItemActionPerformed
        closeAllInternalFrames();
        InscriptionParCertification ipcf = new InscriptionParCertification();
        desktopPane.add(ipcf);
        ipcf.setVisible(true);
        centerInternalFrame(ipcf);
    }//GEN-LAST:event_inscriptionParCertificationMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem certificationMenuItem;
    private javax.swing.JMenuItem certificationParNomMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem etudiantMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem inscriptionMenuItem;
    private javax.swing.JMenuItem inscriptionParCertificationMenuItem;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
